### ISSUE TITLE
Pull request: I'll not..

### ISSUE THREAD

**Issue by jojo12** [Egnarts94/JEM-Project#19]
@Egnarts94:
I like your version 2.3 dev19+ and I didn't find more bugs. For me it's good enough. Some changes I would do, I can and will change with template overrides. 
But I will not answer the pull request, because in earlier cases I was too quick! I am not an expert, even if I find some bugs.
My question is: who will look about the security problems. Who has enough experience with that? is it safe?
EDIT: Thank you for your excellent work!

**Comment by Egnarts94** [comment]
Hello @jojo12 ,
I think there are not more security problems then before because I just duplicated the amount of views. I used the same functionality as the default JEM.
It's okay that you do not respond the pull request. I hope that hoffi will have some time soon...
Edit: What do you think about posting the developer version in the JEM-Responsive Thread in forum for a "public test"?

**Comment by jojo12** [comment]
> What do you think about posting the developer version in the JEM-Responsive Thread in forum for a "public test"?
Hi Egnarts94, 
sorry, I've seen your question only today.
I would say yes.
I think, Hoffi will not have time, respectively he is more interested to find a possibility to give a bit more responsiveness to the tables of the old "template". So he is working on "table-responsive".
But this is not against the JEM-responsive.
I will officially start to work with it on a live site.

**Comment by Egnarts94** [comment]
Okay, then lets do so.
Currently im trying to get better release function instead of manually changing all versions in the files. I think eclipse will help me for that. When i am successfull, I will update the forum post.
