### ISSUE TITLE
Use default values from venue when creating new event

### ISSUE THREAD

**Issue by Hambone68** [Egnarts94/JEM-Project#23]
This is mostly a feature request since you seem to be the most active developer on JEM lately - thanks for your work by the way!
I would like to be able to define event defaults on a per-venue basis (stuff like start time and end time mostly, using custom fields would be fine) and then have those defaults populated in the New Event form when the venue is selected.
Barring that, I'd even be happy with some pointers on where to get started on implementing this myself, but I haven't developed for Joomla since the 1.x days :)

**Comment by jojo12** [comment]
Hi, you sent no information about your version. So I only can say: in JEM 2.2.3 and higher, there are two icons for edit an event. The first one is to edit an existing event. And the second one is for creating a new event with the existing infos. This works in frontend and backend. You can even use an archived event to create a new one. More is not needed and will not be added!

**Comment by Egnarts94** [comment]
@jojo12 
I think he wants to set some values in the custom fields of venues and everytime a new event is created, it should copy the custom-field-values from the venue and use it as date/time etc.

@Hambone68 
I think that is not possible because you are always creating an event before selecting a venue.
If you want to implement that yourself, take a look at the eventcreate view and add some javascript after adding a venue that reads some data and writes it to the event fields.
