### ISSUE TITLE
Change order in Frontend Form editevent

### ISSUE THREAD

**Issue by depebo** [Egnarts94/JEM-Project#42]
Based on @jojo12 forum post few weeks ago:
https://www.joomlaeventmanager.net/forum/feature-requests/10592-todo-change-order-in-frontend-form-editevent
@jojo12 can you confirm what should be going were and post here please. Take screenshot and then cut/move or simply draw on paper or otherwise. Thanks.

**Comment by jojo12** [comment]
![tab2](https://user-images.githubusercontent.com/2960236/57584618-be407300-74dd-11e9-8fff-de1e38b3d182.png)
![tab1](https://user-images.githubusercontent.com/2960236/57584619-be407300-74dd-11e9-98f2-0a47830faa4e.png)
Normally would be WHAT WHEN WHERE, but if you don't have the location, you come into problems, when the location is last. So I took location for the first!
The Basics (I would it rename like that) are first
The Tab EXTENDED or ADVANCED or MORE are things you can let free, only experts should use ist
(like Metatags and custom fields)
The Tab ATTACHMENTS should be the last, because it is the attachment!

The ALIAS should have a placeholder_hint: auto-generate from title. A normal user doesn't know, what he should fill in here (only if you have problems because of doubles you can change alias)

**Comment by depebo** [comment]
@jojo12 do we want to change back end order of field to match as well?
@Egnarts94 let me know if you want me to go ahead with this one (assign to me).

**Comment by jojo12** [comment]
@depebo: I think, in the backend it's ok like it is!

**Comment by Egnarts94** [comment]
Isn't it better to begin to move to J4 than adding new features?

**Comment by jojo12** [comment]
Sorry, but this isn't a new feature, it's only making more userfriendly and can be done passing by.

**Comment by depebo** [comment]
Ys, it is better to move to J4, but I am not sure where to begin with JEM on J4 (namespacing, architecture in general). I am still here to land a hand though.
Looks like we will be using JEM 2.3 for a while, in which case there is a point in making a better UI.
@Egnarts94 Also, what is your plan of merging branches: dev23-depebo has moved ahead of dev23 now.

**Comment by Egnarts94** [comment]
Okay, than lets do that. But when we do that, we need to do for each layout (legacy, alternative, responsive).
I think in a first step, it would be good to only list, what concrete field do you want to have where and which separations. So we can discuss at first, then implement our discussion.

Eg:
Tab: Event
Headline: Details
Fields: 
When
Where
Start Time
End Time
...
Headline: Desc
Field: Description

Tab Other:

@depebo I merged yours into mine. I will do a build, a short test and then merge it into dev23.

**Comment by jojo12** [comment]
Normally I  would prefere WHAT WHEN WHERE.
But when the Location is at the end and your location is not yet saved, you can loose all the fields you just filled before (because this is a needed field). (The only possibility you have is to choose "no location" or to leave).
Tab: Event
Headline: Basics (what where when)
Fields: 
Where
When
Start Time
End Time 
Categories (attention: can be used in different ways)

Headline: Eventdescription
Field: Description

Headline: Eventimage
Field: Image

Headline: Publishing-Options
Fields:
....

Headline: Event Recurrence
Field: Recurrence

Headline: Eventregistration
Fields:
...

Headline: Event Contact Person
Fields: Contact

Tab: Extended
Headline: Custom Fields
Fields:
...

Headline: Meta
Fields:
...

Tab: Attachments
....

**Comment by jojo12** [comment]
To discuss: 
Headline: Publishing-Options
Fields:
Featured
Status
Access
could also be moved to the advanced (extended) tab.
Reason: the normal settings should be changed only in special cases. For the normal user it's too much!

**Comment by Egnarts94** [comment]
My Idea: 

> Tab: Event
> Headline: Basics (what where when)
> Fields:
> Where
> When
> Start Time
> End Time
> Categories (attention: can be used in different ways)

I think you forgot Title and Alias here. Additionally I would remove the headline.
**Tab: Event**
Title
Alias
Start Date, End Date
Start Time, Endtime
Categories
Venue

> Headline: Eventdescription
> Field: Description

I would do that without headline, like it is now. Its obviusly that the big text field should be the description, and the fieldname already exists. So:
Field: Description

> Headline: Eventimage
> Field: Image
> 

I would reorder the following fields. See below.
> Headline: Publishing-Options
> Fields:
> ....
> 
> Headline: Event Recurrence
> Field: Recurrence
> 
> Headline: Eventregistration
> Fields:
> ...
> 
> Headline: Event Contact Person
> Fields: Contact
>
> Tab: Extended
> Headline: Custom Fields
> Fields:
> ...
> 
> Headline: Meta
> Fields:
> ...

 

> Tab: Attachments
> ....

I agree, this should be the last tab.

My full structure suggestion:

**Tab: Event**
Fields:
Title
Alias
Start Date, End Date
Start Time, Endtime
Categories
Venue
Description
Image

**Tab: Extended**
Fields:
Repetition
Contact
Registration
Custom Fields (I am not shure if they should be in an own tab)

**Tab: Publish** (like the typical "Veröffentlichen" Tab of Joomla's content + metadata)
Fields:
Featured
Status
Access
Headline: Metadata
Fields:
Keywords
Description

**Tab: Attachments**
...

The advantages of this structure are:
* The first tab contains only that what you really require for each event.
* More Tabs -> less information overflow per tab

What do you think about?
Is it future safe for future development (Joomla custom fields etc.)?

**Comment by jojo12** [comment]
I agree with your proposal for the structure

**Comment by jojo12** [comment]
Loudly thinking: Not so important, perhaps the editvenue form should have the same consequence of Tabs!

**Comment by Egnarts94** [comment]
Hey @jojo12 ,
can you post a a similar list for editvenue order?

**Comment by jojo12** [comment]
I try but perhaps we have to discuss!
My full structure suggestion:

Tab: Venue
Fields:
Venue
Alias (with hint "auto-generate from Venue")
Street
Zip
City
State
Country
Latitude
Longitude
Add a map link (if possible it would be better to open the geo-data part only, when click on this)
Venue-Description
Venue-Image
Venue-URL (The best place for this, I am not sure!)

Tab: Extended
Fields:
Custom Fields

Tab: Publish (like the typical "Veröffentlichen" Tab of Joomla's content + metadata)
Fields:
Status
Headline: Metadata
Fields:
Keywords
Description

Tab: Attachments
...

**Comment by depebo** [comment]
Event edit front end will be done in the next release, Venue edit please open a separate issue
