### ISSUE TITLE
strange dubbeling in frontend edit_attachments (in editvenue and editevent)

### ISSUE THREAD

**Issue by jojo12** [Egnarts94/JEM-Project#46]
Hi, it seems, I found a bug! in pkg_jem_v2.3.0-dev4.1
in site/com_jem/views/editevent/tmpl/responsive/edit_attachments.php and the same
in site/com_jem/views/editvenue/tmpl/responsive/edit_attachments.php

there is something like a dubbeling:

line 13 ff and line 60 ff (see <legend>)

EDIT: Only the second legend is very strange: better a new key than use a wrong key!

**Comment by jojo12** [comment]
Can this be the reason of the attachment problem issue?

**Comment by Egnarts94** [comment]
I don't see the bug. It is dubbled because I separate existing Attachments from new-added attachments.
Take a look at the difference between Legacy and Responsive View:
![image](https://user-images.githubusercontent.com/14231804/60590915-7cc19b00-9d9d-11e9-8c81-6bbf6c7b76e8.png)
![image](https://user-images.githubusercontent.com/14231804/60590934-89de8a00-9d9d-11e9-9d36-93babe3eabb8.png)

**Comment by jojo12** [comment]
Ok, I see: the first is for existing attachments, and the second is to add an additional attachment.

**Comment by depebo** [comment]
@jojo12  can this be closed?

**Comment by jojo12** [comment]
Yes.
